# Generated by Django 4.2 on 2023-08-21 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='compare_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sold',
        ),
    ]
