# Generated by Django 4.2 on 2023-08-21 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_priceproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
