# Generated by Django 4.2 on 2023-08-21 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceproduct',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
