# Generated by Django 4.0 on 2023-11-21 02:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priceproduct',
            old_name='start_date',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='priceproduct',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='priceproduct',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='priceproduct',
            name='sold',
        ),
        migrations.AddField(
            model_name='priceproduct',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='DiscountPriceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('end_date', models.DateTimeField()),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('price_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.priceproduct')),
            ],
        ),
    ]
