# Generated by Django 4.2 on 2023-11-13 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alpha_2_code', models.CharField(max_length=6, null=True)),
                ('abbreviation_name', models.CharField(blank=True, max_length=50, null=True)),
                ('dial_code', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountryMultilanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('multilanguage_id', models.IntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_multilanguages', to='user.country')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.country'),
        ),
        migrations.DeleteModel(
            name='Countries',
        ),
        migrations.AddConstraint(
            model_name='countrymultilanguage',
            constraint=models.UniqueConstraint(fields=('country', 'multilanguage_id'), name='unique_country_multilanguage_id_combination'),
        ),
    ]
